language: node_js
node_js:
- 6
script:
- npm install
- npm run build
deploy:
  provider: releases
  api_key:
    secure: _
  file: com.siemens.bt.jazz.viewlet.printableworkitems*.zip
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: jazz-community/rtc-myTeams-widget
